// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wealzbxaeugrwfqllzdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlYWx6YnhhZXVncndmcWxsemRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNjc1ODEsImV4cCI6MjA1ODk0MzU4MX0.Cwlru46v-LnZnd2JMIpXdEpd4jlKFUxLgK5W05c7FRI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);